### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by gbbest15** [hcbpassos/drag_select_grid_view#24]
hello, you have done a perfect work for sliding back and onTap to select.

i think there a little issue now, we cant scroll vertically if the items is more than the phone screen.

**Comment by hcbpassos** [comment]
> if the items is more than the phone screen

You don't understand what you mean. Would you mind further elaborating? Maybe an example can help.

**Comment by gbbest15** [comment]
i cant scroll the items in the view. if i have 20 items to display and my phone can only show 10, i cant scroll to view the remaining items

**Comment by hcbpassos** [comment]
I cannot reproduce this in the application provided on example folder. Are you able to reproduce this at 0.4.0? Or do you started facing this issue on 0.5.0.

**Comment by gbbest15** [comment]
i start to face this issue on 0.5.0

**Comment by gbbest15** [comment]
@hcbpassos the scrolling is working fine on 0.4.0 but 0.5.0 is scrolling is not working.

**Comment by hcbpassos** [comment]
So it seems like the issue happens as soon an you select an item. Indeed, i was related to my latest commits. 

Release 0.5.1 got this covered. Thanks!
