### ISSUE TITLE
Need to pop twice after selecting

### ISSUE THREAD

**Issue by vincentderidder** [hcbpassos/drag_select_grid_view#27]
Whenever a user selects anything in de grid, I need to pop twice to go to the previous page. 
The first time, the selection dissapears, the second time we actually go to the previous page.

When selection doesn't get changed, pop works the first time.

**Comment by hcbpassos** [comment]
thanks for openning this issue ❤️ 

that's the expected behavior. do you see any room for improvement?

**Comment by hcbpassos** [comment]
closing due to lack of response.

**Comment by vontdeux** [comment]
having this issue now, i think if there's a bool to set this behaviour would be benefecial.
to give some perspective
I have a screen with tabview, with 3 of this grid inside each tab
and after selected on all 3 grid, to go back, i need to press 3 times to clear the selection, and once to get back to previous screen.

**Comment by HarshavardhanNetha** [comment]
Hello @hcbpassos 
I observed that, in the documentation, it is mentioned, if **DragSelectGridView.unselectOnWillPop** is set to false, we don't need to pop twice after selection. But, unfortunately, I can't find the parameter in DragSelectGridView class.

Can you help me fix this?
